### PR TITLE
style: add custom calculator symbols

### PR DESCRIPTION
**Pull request by M00NJ**
Added the new ui icons. I wanted to add them to the ui as well, but I'm making some newbie mistake when defining the parameters in CalculatorButtons.kt that I coudn't figure out so far, so I'll make this a draft.

### CODE REVIEW

**Review by M00NJ — COMMENTED** [review]
Looks awesome! I should probably create "delete" and "change polarity" icons that match the style.

**Comment by M00NJ** [comment]
I added the new icons. I don't know why, but the delete icon gets rounded off for some reason.
| Original | Drawn |
| --- | --- |
| Screenshot from 2023-11-11 16-23-29 | signal-2023-11-11-162850 |

**Comment by M00NJ** [comment]
Also compare the G-Calc and the font of the text buttons the icons are a bit thick. They're 2.dp stroke width which is standard for the Material icons, so I went with that. but looking at G-Calc, theirs might be 1.5.dp.  So I'll probably swap them out for thinner ones, that match the font width of the text buttons better at some point. Though I'll have to redraw most of them. So I think would should still merge this, since they're still quite nice to look at and swapping them out will be very easy.

**Comment by SuhasDissa** [comment]
> Also compare the G-Calc and the font of the text buttons the icons are a bit thick. They're 2.dp stroke width which is standard for the Material icons, so I went with that. but looking at G-Calc, theirs might be 1.5.dp. So I'll probably swap them out for thinner ones, that match the font width of the text buttons better at some point. Though I'll have to redraw most of them. So I think we should still merge this, since they're still quite nice to look at and swapping them out will be very easy.

I think they're using a custom font instead of icons.
All google apps (like gmail, maps) seem to ignore the system fonts, and use their own font.

**Comment by M00NJ** [comment]
You're right, it could be part of Product Sans (Google's new font). It's a nice font actually. Especially the numbers (6 & 9) look a lot better than Roboto. But unfortunately Android 12 removed the possibility to set a custom font. Still kinda mad about that. 😅

**Comment by M00NJ** [comment]
I don't know if we'd want to go that direction and preset a different font for the you apps. But if we'd make system font a preference, could be a possibility.

**Comment by SuhasDissa** [comment]
is this ready to merge?

**Comment by M00NJ** [comment]
Yes, this can be merged. I was hoping you knew  why it's rounding off the corners of the delete icon though, but we'll figure it out eventually :)

**Comment by M00NJ** [comment]
Should I merge this?
Also I think we could do the first release soon :)

**Comment by SuhasDissa** [comment]
Feel free to

**Pull request merged**
