### PR TITLE
style: keypad ui improvements

### PR DESCRIPTION
**Pull request by M00NJ**
I forgot to take a screenshot before.

After:
Calc

### CODE REVIEW

**Comment by M00NJ** [comment]
Damn. I deleted the wrong branch :/

**Comment by SuhasDissa** [comment]
You cant reopen this PR again.
But I can merge the changes

Is it OK?

**Comment by M00NJ** [comment]
> Is it OK?

That's great!

**Comment by SuhasDissa** [comment]
8107551

**Comment by M00NJ** [comment]
BTW the divider in the text field is not visible with dark mode enabled (see screenshot). `outlineVariant` is the only color that doesn't change dynamically and it also has this slight purple tint. I don't know why haven't changed that. I usually use `surfaceVariant`, but that's already the background color, so it doesn't work here. We should probably choose a different color, or just remove the divider.

**Comment by SuhasDissa** [comment]
We could use `colorScheme.background`

**Comment by M00NJ** [comment]
signal-2023-12-10-132718

It's visible. But I think it would look cleaner without a divider, like G-Calc.

**Comment by SuhasDissa** [comment]
is this any good?

**Comment by M00NJ** [comment]
Just had a similar idea. Yes, this looks much better :)  Were has the primary color of the `eqal` button gone though?

**Comment by SuhasDissa** [comment]
Maybe because of the lightmode?

**Comment by M00NJ** [comment]
Another ui related thing. The icons in the converter grid have a fixed color. In light mode it looks good since it matches the font color, but in dark mode not so much. How do I change the image color without duplicating code?

Screenshot from 2023-12-10 14-03-50

**Comment by M00NJ** [comment]
> Maybe because of the lightmode?

That's probably it

**Comment by SuhasDissa** [comment]
> Another ui related thing. The icons in the converter grid have a fixed color. In light mode it looks good since it matches the font color, but in dark mode not so much. How do I change the image color without duplicating code?
> 

I already fixed the issue update your local repos

**Pull request closed without merging**
