### PR TITLE
fix: button colors

### PR DESCRIPTION
**Pull request by M00NJ**
This makes the button colors match G-Calc.

| Before | After |
| --- | --- |
| signal-2023-11-09-125116_002 | signal-2023-11-09-125020_003 |

### CODE REVIEW

**Comment by SuhasDissa** [comment]
I think it would be better to change the default background color in the CalculatorButton function.

**Comment by M00NJ** [comment]
I  added another commit for the rest of the buttons and updated the PR description.

**Comment by M00NJ** [comment]
> I think it would be better to change the default background color in the CalculatorButton function.

You're right. I tried but I'm probably doing it wrong. This doesn't work: 
Screenshot from 2023-11-09 13-25-29

**Comment by SuhasDissa** [comment]
image

I meant this

**Comment by M00NJ** [comment]
> I meant this

Right 😅

Should be fixed now.

**Pull request merged**
